### ISSUE TITLE
requests dependency not resolved

### ISSUE THREAD

**Issue by unbekanntes-pferd** [nuclia/nucliadb#656] opened 2023-03-10 17:51 UTC
**Describe the bug**
- Created new project via poetry
- added nucliadb-sdk via `poetry add nucliadb-sdk`
- ran `main.py` (a FastAPI application)
- received error on `get_or_create()` - unresolved import (`requests`)

**Steps to reproduce (if applicable)**

1. Create empty project in poetry 
2. Do NOT install requests (virtual environment)
3. run get_or_create (or anything else)

**Expected behavior**
No import error (requests should be marked as a dependency if needed requirements.txt - it is not)

importing requests occurs here: https://github.com/nuclia/nucliadb/blob/main/nucliadb_sdk/nucliadb_sdk/client.py#L25 
requirements.txt here: https://github.com/nuclia/nucliadb/blob/main/nucliadb_sdk/requirements.txt

```
pip3 list | grep nucliadb
nucliadb-models    2.4.0.post27
nucliadb-protos    2.4.0.post27
nucliadb-sdk       2.4.0.post27
```

**Comment by mesejo** [comment] 2023-03-19 16:40
Hey! I would like to work on this 😄. The [requirements.txt](https://github.com/nuclia/nucliadb/blob/main/nucliadb_sdk/requirements.txt) file does include `requests`: 
```
httpx
requests
nucliadb-models
```
So I guess the OP is referring to making it a dependency when using poetry for installing it, right?  If that is the case would it be helpful to make other modules poetry-ready? (easy to install with poetry). 

As a side note, this could be solved by just adding instructions to add the requirements.txt from poetry, using:
```bash
poetry add $( cat requirements.txt ) 
```

Other solutions can be found [here](https://stackoverflow.com/q/62764148/4001592)

**Comment by lferran** [comment] 2023-03-20 07:31
Hi @unbekanntes-pferd @mesejo I tested it with the latest version of `nucliadb_sdk` and the issue is resolved. The requests library gets installed. 

It was fixed in this PR: https://github.com/nuclia/nucliadb/pull/666/files#diff-9b32eefd4cd036ad2d21dcfb57bdd70f8d9fbefc0fd45b52d7c8e03420963970R2

Closing this for now, but please comment if you still have problems.

**Closed by lferran** 2023-03-20 07:31 UTC
Labels: bug
